In [ ]:
import pandas as pd

<h1>converting data into Dataframe</h1>

In [13]:
df=pd.read_csv("data.csv")

In [15]:
df

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Odisha,Sambalpur,Sahaspur APMC,Tomato,Other,Local,27/10/2026,1800.0,1900.0,1850.0
1,Odisha,Sambalpur,Sahaspur APMC,Raddish,Other,Local,27/10/2026,1700.0,1800.0,1750.0
2,Chattisgarh,Khairagarh Chhuikhadan Gandai,Kheragarh APMC,Soyabean,Soyabeen,Non-FAQ,27/10/2026,5200.0,5400.0,5300.0
3,Andhra Pradesh,Prakasam,Maddipadu APMC,Paddy(Common),B P T,FAQ,27/10/2026,2800.0,2800.0,2800.0
4,Keralam,Wayanad,Mananthavady Market,Rubber,Other,Local,27/10/2026,27000.0,27000.0,27000.0
...,...,...,...,...,...,...,...,...,...,...
17343,Rajasthan,Kota,Khatauli APMC,Black Gram(Urd Beans)(Whole),Black Gram (Whole),Local,27/10/2026,4000.0,8185.0,7000.0
17344,Rajasthan,Tonk,Dooni APMC,Maize,Hybrid,Local,27/10/2026,2150.0,2450.0,2200.0
17345,Rajasthan,Tonk,Dooni APMC,Barley(Jau),Dara,Local,27/10/2026,2850.0,3000.0,2925.0
17346,Rajasthan,Tonk,Dooni APMC,Black Gram(Urd Beans)(Whole),Black Gram (Whole),Local,27/10/2026,6400.0,7275.0,6838.0
17347,West Bengal,Coochbehar,Mekhliganj APMC,Brinjal,Brinjal,FAQ,27/10/2026,5200.0,5800.0,5500.0

<h1>DataFeatures</h1>

In [22]:
shape=df.shape
shape

(17348, 10)

In [25]:
columns=df.columns
columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price',
       'Modal_x0020_Price'],
      dtype='object')

In [31]:
head=df.head
head

<bound method NDFrame.head of                 State                       District               Market  \
0              Odisha                      Sambalpur        Sahaspur APMC
1              Odisha                      Sambalpur        Sahaspur APMC
2         Chattisgarh  Khairagarh Chhuikhadan Gandai       Kheragarh APMC
3      Andhra Pradesh                       Prakasam       Maddipadu APMC
4             Keralam                        Wayanad  Mananthavady Market
...               ...                            ...                  ...
17343       Rajasthan                           Kota        Khatauli APMC
17344       Rajasthan                           Tonk           Dooni APMC
17345       Rajasthan                           Tonk           Dooni APMC
17346       Rajasthan                           Tonk           Dooni APMC
17347     West Bengal                     Coochbehar      Mekhliganj APMC

                          Commodity             Variety    Grade Arrival_Date  \
0                            Tomato               Other    Local   27/10/2026
1                           Raddish               Other    Local   27/10/2026
2                          Soyabean            Soyabeen  Non-FAQ   27/10/2026
3                     Paddy(Common)               B P T      FAQ   27/10/2026
4                            Rubber               Other    Local   27/10/2026
...                             ...                 ...      ...          ...
17343  Black Gram(Urd Beans)(Whole)  Black Gram (Whole)    Local   27/10/2026
17344                         Maize              Hybrid    Local   27/10/2026
17345                   Barley(Jau)                Dara    Local   27/10/2026
17346  Black Gram(Urd Beans)(Whole)  Black Gram (Whole)    Local   27/10/2026
17347                       Brinjal             Brinjal      FAQ   27/10/2026

       Min_x0020_Price  Max_x0020_Price  Modal_x0020_Price
0               1800.0           1900.0             1850.0
1               1700.0           1800.0             1750.0
2               5200.0           5400.0             5300.0
3               2800.0           2800.0             2800.0
4              27000.0          27000.0            27000.0
...                ...              ...                ...
17343           4000.0           8185.0             7000.0
17344           2150.0           2450.0             2200.0
17345           2850.0           3000.0             2925.0
17346           6400.0           7275.0             6838.0
17347           5200.0           5800.0             5500.0

[17348 rows x 10 columns]>

In [33]:
print(df.columns.tolist())

['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', 'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price', 'Modal_x0020_Price']

In [34]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17348 entries, 0 to 17347
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              17348 non-null  object
 1   District           17348 non-null  object
 2   Market             17348 non-null  object
 3   Commodity          17348 non-null  object
 4   Variety            17348 non-null  object
 5   Grade              17348 non-null  object
 6   Arrival_Date       17348 non-null  object
 7   Min_x0020_Price    17348 non-null  float64
 8   Max_x0020_Price    17348 non-null  float64
 9   Modal_x0020_Price  17348 non-null  float64
dtypes: float64(3), object(7)
memory usage: 1.3+ MB
None

In [35]:
df.head(10)

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_x0020_Price,Max_x0020_Price,Modal_x0020_Price
0,Odisha,Sambalpur,Sahaspur APMC,Tomato,Other,Local,27/10/2026,1800.0,1900.0,1850.0
1,Odisha,Sambalpur,Sahaspur APMC,Raddish,Other,Local,27/10/2026,1700.0,1800.0,1750.0
2,Chattisgarh,Khairagarh Chhuikhadan Gandai,Kheragarh APMC,Soyabean,Soyabeen,Non-FAQ,27/10/2026,5200.0,5400.0,5300.0
3,Andhra Pradesh,Prakasam,Maddipadu APMC,Paddy(Common),B P T,FAQ,27/10/2026,2800.0,2800.0,2800.0
4,Keralam,Wayanad,Mananthavady Market,Rubber,Other,Local,27/10/2026,27000.0,27000.0,27000.0
5,Keralam,Wayanad,Mananthavady Market,Bitter gourd,Bitter Gourd,FAQ,27/10/2026,3800.0,4000.0,3900.0
6,Keralam,Wayanad,Mananthavady Market,Cucumbar(Kheera),Cucumbar,FAQ,27/10/2026,1600.0,1800.0,1700.0
7,Madhya Pradesh,Mandla,Krishi Upaj Mandi Samiti Bichhiya,Wheat,Wheat,FAQ,27/10/2026,2520.0,2550.0,2550.0
8,Madhya Pradesh,Mandla,Krishi Upaj Mandi Samiti Bichhiya,Green Peas,Pea,FAQ,27/10/2026,3200.0,3200.0,3200.0
9,Madhya Pradesh,Mandla,Krishi Upaj Mandi Samiti Bichhiya,Kutki,Kutki,FAQ,27/10/2026,7600.0,7700.0,7700.0

In [ ]:
df["Arrival_Date"] = pd.to_datetime(df["Arrival_Date"], errors="coerce")

0       NaT
1       NaT
2       NaT
3       NaT
4       NaT
         ..
17343   NaT
17344   NaT
17345   NaT
17346   NaT
17347   NaT
Name: Arrival_Date, Length: 17348, dtype: datetime64[ns]

In [46]:
print(df["Arrival_Date"].head())
print(df["Arrival_Date"].dtype)

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Arrival_Date, dtype: datetime64[ns]
datetime64[ns]

In [51]:
df.columns = df.columns.str.strip()

df["Commodity"].value_counts().head(20)

Commodity
Tomato                   556
Brinjal                  556
Onion                    549
Potato                   509
Paddy(Common)            475
Maize                    454
Green Chilli             445
Bhindi(Ladies Finger)    444
Wheat                    441
Cauliflower              397
Banana                   394
Cabbage                  389
Bottle gourd             379
Bitter gourd             366
Soyabean                 365
Pumpkin                  325
Cucumbar(Kheera)         320
Raddish                  305
Carrot                   291
Ginger(Green)            263
Name: count, dtype: int64